Repository likeLion-FE4-RP11/Asparagus, pull requests merged in 2023-04, with the labels that each got.

#174 [Modify] 사용자가 보기 편한 카테고리 아코디언으로 수정
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.styled.jsx
Labels: ✏️ Modify

#178 [Feat] 업로드 페이지 특정 상황에서 Notification창 띄우기
  package-lock.json
  package.json
  src/pages/UploadPage/UploadPage.jsx
Labels: ✨ Feature

#183 [Feat] 로딩스피너 컴포넌트 구현 #179
  src/assets/LoadingSpinnerGif.gif
  src/components/LoadingSpinner/LoadingSpinner.jsx
  src/components/LoadingSpinner/LoadingSpinner.styled.jsx
  src/components/index.js
  src/pages/SignUp/SignUpPage.jsx
Labels: ✨ Feature

#182 [Refactor]로그인 페이지 유효성검사
  package-lock.json
  package.json
  src/pages/SignIn/SignInPage.jsx
Labels: 🔨 Refactor

#185 [Fix] 메인페이지 이미지 렌더링 리팩토링
  src/components/Swiper/MainSwiper.jsx
  src/pages/Home/HomePage.jsx
Labels: 🐞 BugFix, ✏️ Modify

#197 [로그인] 로그인 유효성 검사 및 반응형 CSS
  src/components/Button/LoginButton.jsx
  src/components/Container/Container.jsx
  src/components/FormInput/FormInput.styled.jsx
  src/components/Swiper/Swiper.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.styled.jsx
  src/pages/SignUp/SignUpPage.styled.jsx
  src/styles/global.css
Labels: 🔨 Refactor, ✏️ Modify

#196 [Refactor] 카테고리 페이지 반응형 수정
  src/components/Button/ToggleButton.jsx
  src/components/DesignParagraph/DesignParagraph.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/Notification/Notification.styled.jsx
  src/components/UseHover/UseHover.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
Labels: 🔨 Refactor

#199 [Refactor] 푸터 반응형 수정
  src/components/Footer/Footer.styled.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
Labels: 🔨 Refactor

#202 [Refactor] 업로드 페이지 반응형 수정
  src/components/Accordion/Accordion.styled.jsx
  src/components/Input/ImageUploadInput.styled.jsx
  src/components/UploadPage/ImageDescription.jsx
  src/pages/UploadPage/UploadPage.styled.jsx
Labels: 🔨 Refactor

#204 [Refactor] 회원가입, 메인페이지 반응형 수정
  src/assets/LogoIcon.jsx
  src/components/Category/Category.jsx
  src/components/CategoryTitle/CategoryTitle.jsx
  src/components/CheckBox/CheckBox.styled.jsx
  src/components/Header/Header.jsx
  src/components/Nav/Nav.styled.jsx
  src/components/SignUpFormInput/SignUpFormInput.styled.jsx
  src/components/Swiper/MainSwiper.styled.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Home/HomePage.styled.jsx
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.styled.jsx
Labels: 🔨 Refactor

#205 [Feat] develop -> main 반응형 리팩토링작업 배포
  src/assets/LogoIcon.jsx
  src/components/Accordion/Accordion.styled.jsx
  src/components/Button/LoginButton.jsx
  src/components/Button/ToggleButton.jsx
  src/components/Category/Category.jsx
  src/components/CategoryTitle/CategoryTitle.jsx
  src/components/CheckBox/CheckBox.styled.jsx
  src/components/DesignParagraph/DesignParagraph.jsx
  src/components/Footer/Footer.styled.jsx
  src/components/FormInput/FormInput.styled.jsx
  src/components/Header/Header.jsx
  src/components/Input/ImageUploadInput.styled.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/Nav/Nav.styled.jsx
  src/components/Notification/Notification.styled.jsx
  src/components/SignUpFormInput/SignUpFormInput.styled.jsx
  src/components/Swiper/MainSwiper.styled.jsx
  src/components/Swiper/Swiper.jsx
  src/components/UploadPage/ImageDescription.jsx
  src/components/UseHover/UseHover.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Home/HomePage.styled.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.styled.jsx
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.styled.jsx
  src/pages/UploadPage/UploadPage.styled.jsx
  src/styles/global.css
Labels: 🔨 Refactor
