Repository likeLion-FE4-RP11/Asparagus, pull requests merged in 2023-03, with the labels that each got.

#27 [Feat] Swiper 컴포넌트 생성
  package-lock.json
  package.json
  src/app/App.jsx
  src/components/Swiper/Pagination.module.css
  src/components/Swiper/Swiper.jsx
  src/components/index.js
Labels: ✨ Feature

#25 [Feat] 푸터 컴포넌트 생성
  src/app/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Footer/Logo.png
Labels: ✨ Feature

#26 [Feat] 이미지 컴포넌트 생성
  package-lock.json
  package.json
  src/app/App.jsx
  src/assets/gallery-icon.png
  src/assets/test.jpg
  src/components/ImageContainer/BaseImage.jsx
  src/components/ImageContainer/ImageContainer.jsx
  src/components/ImageContainer/ImageContainer.module.css
  src/components/index.js
Labels: ✨ Feature

#31 [Feat] Top 버튼 컴포넌트 생성
  package-lock.json
  package.json
  src/app/App.jsx
  src/assets/topbutton-icon.svg
  src/components/Button/TopButton.jsx
  src/components/Button/TopButton.module.css
  src/components/Button/TopButtonTest.jsx
  src/components/index.js
Labels: ✨ Feature

#34 [Feat] 디자인 문구 컴포넌트 구현
  src/app/App.jsx
  src/components/DesignParagraph/DesignParagraph.jsx
  src/components/DesignParagraph/DesignParagraph.module.css
  src/components/index.js
Labels: ✨ Feature

#29 [Feat] 토글 버튼 컴포넌트 생성
  .vscode/settings.json
  package-lock.json
  src/app/App.jsx
  src/components/Button/ButtonToggle.jsx
  src/components/Button/ButtonToggle.module.css
  src/components/index.js
Labels: ✨ Feature

#35 [Feat] 삭제 버튼 컴포넌트 생성#23
  src/app/App.jsx
  src/components/Button/DeleteButton.jsx
  src/components/Button/DeleteButton.module.css
  src/components/index.js
  src/theme/utils.js
Labels: ✨ Feature

#30 [Feat] CategoryTitle 컴포넌트 생성
  src/app/App.jsx
  src/components/CategoryTitle/CategoryTitle.jsx
  src/components/CategoryTitle/CategoryTitle.module.css
  src/components/index.js
Labels: ✨ Feature

#36 [Feat] 좋아요 컴포넌트 생성
  src/app/App.jsx
  src/assets/Heart.png
  src/assets/empty-heart.png
  src/components/LikeButton/LikeButton.jsx
  src/components/LikeButton/LikeButton.module.css
Labels: ✨ Feature

#43 [Refactor] 카테고리 타이틀 styled-component로 변경
  package-lock.json
  src/components/CategoryTitle/CategoryTitle.jsx
  src/components/CategoryTitle/CategoryTitle.module.css
Labels: 🔨 Refactor

#40 [Refactor] Swiper module.css->styled-component 변경
  src/components/Swiper/Pagination.module.css
  src/components/Swiper/Swiper.jsx
Labels: 🔨 Refactor

#54 [Refactor] Toggle버튼 스타일 styled-component로 변경 #52
  src/app/App.jsx
  src/components/Button/ButtonToggle.jsx
  src/components/Button/ButtonToggle.module.css
  src/components/Button/DeleteButton.jsx
  src/components/Button/DeleteButton.module.css
  src/components/Button/ToggleButton.jsx
  src/components/index.js
Labels: 🔨 Refactor

#57 [Feat] 업로드 이미지 input 컴포넌트 생성
  src/app/App.jsx
  src/assets/imageUpload-icon.svg
  src/components/Input/ImageUploadInput.jsx
  src/components/Input/ImageUploadInput.styled.jsx
  src/components/index.js
  src/theme/utils.js
Labels: ✨ Feature

#56 [Feat] SeeMore 컴포넌트 생성
  src/app/App.jsx
  src/components/Button/SeeMoreButton.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/SeeMoreImage/SeeMoreImg.jsx
  src/components/index.js
Labels: ✨ Feature

#53 [Refactor] 푸터 & 좋아요 컴포넌트 스타일 styled-component로 변경
  src/app/App.jsx
  src/assets/Logo.png
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Footer/Footer.styled.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/LikeButton/LikeButton.module.css
  src/components/index.js
Labels: 🔨 Refactor

#62 [Refactor] Top버튼 애니메이션 framer-motion으로 변경 #61
  package-lock.json
  package.json
  src/components/Button/TopButton.jsx
Labels: 🔨 Refactor

#69 [Feat] 마우스오버 컴포넌트 생성
  src/components/UseHover/UseHover.jsx
  src/components/index.js
Labels: ✨ Feature

#67 [카테고리] Notification 창 띄우기 기능 구현
  .vscode/settings.json
  index.html
  src/assets/lock-Icon.svg
  src/components/Button/ToggleButton.jsx
  src/components/Notification/Notification.jsx
  src/components/Notification/Notification.styled.jsx
Labels: ✨ Feature

#63 [업로드] 이미지 업로드 설명 input 창
  src/app/App.jsx
  src/components/UploadPage/ImageDescription.jsx
  src/components/index.js
Labels: ✨ Feature

#70 [Feat] Accordion 컴포넌트 생성
  src/app/App.jsx
  src/assets/arrow-down.svg
  src/assets/arrow-up.svg
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.styled.jsx
  src/components/index.js
Labels: ✨ Feature

#101 [Refactor] DeleteButton onClick사용
  src/components/Button/DeleteButton.jsx
Labels: 🔨 Refactor

#97 [Feature] 페이지 컴포넌트 배치
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.styled.jsx
  src/components/Button/SeeMoreButton.jsx
  src/components/Input/ImageUploadInput.jsx
  src/components/Input/ImageUploadInput.styled.jsx
  src/components/UploadPage/ImageDescription.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/UploadPage.styled.jsx
Labels: ✨ Feature, 🔨 Refactor

#98 [로그인] formInput 및 로그인 버튼 컴포넌트 구현
  src/components/Button/Button.jsx
  src/components/Button/LoginButton.jsx
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.styled.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/index.js
  src/pages/SignIn/SignInPage.jsx
Labels: ✨ Feature

#106 [회원가입] Html&Css 마크업 및 SignUpFormInput 컴포넌트 구현
  src/components/Accordion/Accordion.jsx
  src/components/SignUpFormInput/SignUpFormInput.jsx
  src/components/SignUpFormInput/SignUpFormInput.styled.jsx
  src/components/index.js
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPase.styled.jsx
Labels: ✨ Feature

#111 [회원가입] 체크박스 컴포넌트 구현, 회원가입 페이지 마크업 완성
  src/assets/SignUp_main.jpg
  src/components/Accordion/Accordion.jsx
  src/components/CheckBox/CheckBox.jsx
  src/components/CheckBox/CheckBox.styled.jsx
  src/components/FormInput/FormInput.jsx
  src/components/SignUpFormInput/SignUpFormInput.jsx
  src/components/SignUpFormInput/SignUpFormInput.styled.jsx
  src/components/index.js
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPase.styled.jsx
  src/styles/global.css
Labels: ✨ Feature

#109 [Feat] delete 버튼 클릭시 input 내용 초기화
  src/components/Input/ImageUploadInput.jsx
  src/components/UploadPage/ImageDescription.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: ✨ Feature

#126 [Feat] 스와이퍼에 firestore에 있는 이미지 url로 불러오기
  src/components/Category/Category.jsx
  src/components/CategoryTitle/CategoryTitle.jsx
  src/components/Swiper/MainSwiper.jsx
  src/components/Swiper/MainSwiper.styled.jsx
  src/components/index.js
  src/pages/Home/HomePage.jsx
Labels: ✨ Feature

#112 [Feat] 업로드 버튼 클릭시 image 데이터 제작
  src/components/Accordion/Accordion.jsx
  src/components/Input/ImageUploadInput.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/utils/index.js
  src/utils/utils.js
Labels: ✨ Feature

#128 [Feat] 로그인 파이어베이스 기능 및 소셜로그인 컴포넌트
  src/app/App.jsx
  src/assets/Google-logo.svg
  src/assets/facebook-logo.svg
  src/components/Button/LoginButton.jsx
  src/components/Container/Container.jsx
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.styled.jsx
  src/firebase/auth/GoogleLogin.js
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignPage.styled.jsx
Labels: ✨ Feature

#129 [Feat] 업로드 버튼 클릭 시 이미지데이터 firestore에 저장
  src/pages/UploadPage/UploadPage.jsx
  src/utils/utils.js
Labels: ✨ Feature

#135 [Feat] 메인페이지 배치, recent Image에 실시간 이미지 최신순 렌더링
  src/components/Button/SeeMoreButton.jsx
  src/components/Category/Category.jsx
  src/components/ImageContainer/BaseImage.jsx
  src/components/RecentImageTitle/RecentImageTitle.jsx
  src/components/SeeMoreImage/SeeMoreImg.jsx
  src/components/index.js
  src/pages/Home/HomePage.jsx
  src/pages/Home/HomePage.styled.jsx
Labels: ✨ Feature

#139 [Feat] 회원가입 Firestore 연결 완료
  src/components/CheckBox/CheckBox.jsx
  src/firebase/firestore/useCreateAuthUser.js
  src/pages/SignUp/SignUpPage.jsx
Labels: ✨ Feature

#133 [Feat] Delete 버튼으로 삭제시에 firestore의 이미지 데이터 삭제
  src/assets/test.jpg
  src/assets/test.svg
  src/components/Button/DeleteButton.jsx
  src/components/ImageContainer/ImageContainer.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/UseHover/UseHover.jsx
  src/pages/Categories/CategoriesPage.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
  src/utils/categoryUtils.js
Labels: ✨ Feature

#142 [Feat] 메인페이지 동적라우팅 완성
  src/app/App.jsx
  src/components/Category/Category.jsx
Labels: ✨ Feature

#143 [Feat] 좋아요 버튼 실시간 업데이트로 렌더링 구현
  src/components/LikeButton/LikeButton.jsx
  src/components/UseHover/UseHover.jsx
Labels: ✨ Feature

#144 [Feat] 회원정보 firestore 컬렉션 utils 생성
  src/components/CheckBox/CheckBox.jsx
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPase.styled.jsx
  src/utils/utils.js
Labels: ✨ Feature

#145 [공통] 중첩 라우팅을 이용한 페이지 구성
  src/app/App.jsx
  src/assets/BackgroundImage.svg
  src/assets/LogIn.jpg
  src/components/Button/LoginButton.jsx
  src/components/Footer/Footer.jsx
  src/components/Layout/Layout.jsx
  src/components/LikeButton/LikeButton.jsx
  src/pages/Home/HomePage.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignPage.styled.jsx
Labels: ✨ Feature

#149 [Feat] 유저 Context API 구현
  src/app/App.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.module.css
  src/contexts/AuthUser.jsx
  src/main.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignUp/SignUpPage.jsx
Labels: ✨ Feature

#151 [Feat] context api 를 통한 토글시 다크 모드 기능 및 공개 비공개 구현
  src/components/Button/ToggleButton.jsx
  src/components/Container/Container.jsx
  src/components/Context/ThemeContext.jsx
  src/components/DesignParagraph/DesignParagraph.jsx
  src/components/Footer/Footer.styled.jsx
  src/components/ImageContainer/ImageContainer.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/index.js
  src/pages/Categories/CategoriesPage.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
  src/theme/theme.js
Labels: ✨ Feature

#160 [Refactor] 헤더 컴포넌트 테마변경
  src/assets/Dark.svg
  src/assets/Light.svg
  src/assets/Logo.svg
  src/components/Header/Header.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.styled.jsx
  src/contexts/ThemeContext.jsx
  src/pages/Categories/CategoriesPage.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
  src/theme/theme.js
Labels: ✏️ Modify

#168 [Bug] SEEMORE 탭에서 이미지 안뜨는 오류 해결 #167
  src/pages/Home/HomePage.jsx
Labels: 🐞 BugFix

#170 [Feat] Develop -> Main 브랜치
  dist/vite.svg
  package-lock.json
  src/app/App.jsx
  src/components/ImageContainer/ImageContainer.jsx
  src/components/LikeButton/LikeButton.jsx
  src/components/Swiper/MainSwiper.jsx
  src/pages/Categories/CategoriesPage.jsx
  src/pages/Categories/CategoriesPage.styled.jsx
  src/pages/Home/HomePage.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.styled.jsx
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.styled.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/utils/utils.js
Labels: ✨ Feature, 🔨 Refactor
